# https://github.com/realm/SwiftLint
disabled_rules:
  - closure_parameter_position
  - fallthrough
  - opening_brace
  - trailing_whitespace
  - vertical_whitespace
included:
  - Sources
excluded:
  - Examples
  - Xcode

cyclomatic_complexity:
  ignores_case_statements: true
file_length:
  warning: 750
function_body_length:
  warning: 200
  error: 300
identifier_name:
  min_length:
    warning: 1
nesting:
  type_level:
    warning: 2
type_name:
  max_length:
    warning: 50
type_body_length:
  warning: 300
  error: 400
