# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BVSwiftDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for BVSwiftDemo
  
  pod 'BVSwift/BVAnalytics', :path => "../../"
  pod 'BVSwift/BVCommon', :path => "../../"
  pod 'BVSwift/BVConversations', :path => "../../"
  pod 'BVSwift/BVCurations', :path => "../../"
  pod 'BVSwift/BVRecommendations', :path => "../../"
  pod 'BVSwift/BVProductSentiments', :path => "../../"
  pod 'XLActionController'
  pod 'Google-Mobile-Ads-SDK','7.61.0'
  pod 'FontAwesomeKit/FontAwesome'
  pod 'SDWebImage'
  pod 'HCSStarRatingView'
  pod 'OHHTTPStubs/Swift'
  pod 'SwiftyJSON'
  pod 'SDForms', :git => 'https://github.com/austimkelly/SDForms.git', :branch => 'master'
  
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.6'
    end
  end
end
