name: Swift

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Select Xcode
      run: sudo Xcode-select -switch /Applications/Xcode_10.2.app

    - name: Build
      run: '././ci_scripts/build_framework.sh'
    
    - name: Run tests
      run: '././ci_scripts/run_tests.sh'